name: Generate Interactive Pinouts

on:
  push:
    branches: [ main ]  
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Generate Pinouts
      uses: chuckwagoncomputing/interactive-pinout@2.1
      with:
        mapping-path: ./Hardware/pinout/*.yaml
        warnings: "false"
        warning-dupe: "error"
        columns: |
          {
          "pin":"Pin Number",
          "type":"Type",
          "function":"Typical Function",
          "color":"Pigtail Color"
          }
        print-columns: |
          [
          "function"
          ]
        colors: |
          {
          "12v":"yellow";
          "12V":"yellow";
          "5v":"red",
          "5V":"red",
          "at":"green",
          "av":"brown",
          "can":"blue",
          "din":"lime",
          "etb":"darkcyan",
          "gnd":"darkgreen",
          "gp_high":"aqua",
          "gp_low":"aquamarine",
          "gp_pp":"cyan",
          "hall":"darkolivegreen",
          "hl":"gold",
          "hs":"indigo",
          "ign":"magenta",
          "inj":"maroon",
          "ls":"lightgreen",
          "mr":"firebrick",
          "pgnd":"coral",
          "sgnd":"olive",
          "usb":"lightseagreen",
          "vr":"sienna"
          }
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: pinouts
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
